Added a feature to update an existing cart
poorna-soysa/grpc-demo pull request #3
Opened 2024-11-04 18:50 UTC by gvieira-dutra

Added a Put route to the ShoppingCart Features, this allows the API to update the number of Items and their price on an existing cart.

2024-11-05 08:45 UTC, sunnynagavo commented on Services/ShoppingCart/ShoppingCart.Api/Data/CachedShoppingCartRepository.cs
> +
nit: remove this extra line

2024-11-05 08:46 UTC, sunnynagavo commented on Services/ShoppingCart/ShoppingCart.Api/Data/IShoppingCartRepository.cs
> +
+1, remove this extra line

2024-11-05 09:15 UTC, sunnynagavo approved these changes
rest everything Looks good to me

2024-11-05 12:56 UTC, gvieira-dutra commented
thanks for the feedback, I removed the extra lines

2024-11-06 00:01 UTC, poorna-soysa requested changes

2024-11-06 00:01 UTC, poorna-soysa commented on Services/ShoppingCart/ShoppingCart.Api/Features/ShoppingCart/UpdateShoppingCart/UpdateShoppingCartEndpoint.cs
> +            return Results.Created($"/api/shopping-cart/{response.UserName}",
Return should be Results.OK() or Results.NoContent();

2024-11-06 00:01 UTC, poorna-soysa commented on Services/ShoppingCart/ShoppingCart.Api/Features/ShoppingCart/UpdateShoppingCart/UpdateShoppingCartEndpoint.cs
> +        .Produces<UpdateShoppingCartResponse>(StatusCodes.Status201Created)
Status either 200 or 204.

2024-11-07 00:19 UTC, poorna-soysa requested changes

2024-11-07 00:19 UTC, poorna-soysa commented on Services/ShoppingCart/ShoppingCart.Api/Features/ShoppingCart/UpdateShoppingCart/UpdateShoppingCartEndpoint.cs
> +        app.MapPut("/api/shopping-cart", async (UpdateShoppingCartRequest request, ISender sender) =>
Update endpoint should be /api/shopping-cart/{userName}

2024-11-07 00:19 UTC, poorna-soysa commented on Services/ShoppingCart/ShoppingCart.Api/Features/ShoppingCart/UpdateShoppingCart/UpdateShoppingCartEndpoint.cs
> +        .ProducesProblem(StatusCodes.Status400BadRequest)
SHould be .ProducesProblem(StatusCodes.Status400BadRequest) and .ProducesProblem(StatusCodes.Status404NotFound)

2024-11-08 00:55 UTC, poorna-soysa approved these changes

2024-11-08 00:55 UTC, merged